name: livedom_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # http 통신
  http: ^1.1.2

  # 날짜 선택
  flutter_datetime_picker_plus: ^2.1.0

  # 날짜 포맷
  intl: ^0.19.0

  # 달력 선택
  calendar_date_picker2: ^0.5.3

  # 이미지 슬라이드
  # carousel_slider: ^4.2.1

  # 카카오 sdk
  kakao_flutter_sdk: ^1.8.0 

  # 구글 폰트
  google_fonts: ^6.1.0

  # provider (상태 공유 - 로그인 인증정보 공유)
  provider: ^6.1.1

  # 파일 
  path_provider: ^2.1.2
  
  # io
  dio: ^5.4.0

  json_annotation: ^4.8.1

  platform: ^3.1.4

  # 공유 환경설정
  shared_preferences: ^2.2.2

  crypto: ^3.0.3

  encrypt: ^5.0.3

  # 플러터에서 웹 콘텐츠를 표시
  webview_flutter: ^4.4.4

  # user 관련 dependencies
  
  # Flutter 앱의 상태 관리, 네비게이션, 다이얼로그 및 다양한 편리한 기능들을 제공하는 강력한 상태 관리 라이브러리
  get: ^4.6.6

  # 안전한 저장소
  flutter_secure_storage: ^9.0.0

  # flutter_svg
  flutter_svg: ^2.0.9

  # shimmer 반짝반짝 빛나는 스켈레톤
  shimmer: ^3.0.0

  #qr스캐너
  qr_code_scanner: ^1.0.1
  
  # 이미지 슬라이드
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.3.9

  # html to view 파싱
  flutter_html: 3.0.0-beta.2
  # 이미지 피커(삽입)
  image_picker: ^0.8.9

  # html editor
  html_editor_enhanced: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
    - images/


flutter_icons:
  android: true
  ios: true
  image_path: "images/LIVE.png"